### ISSUE TITLE
Where are the download files?

### ISSUE THREAD

**Issue by DanLong** [stefankueng/tools#32]
I apologize in advance, this is probably a stupid question.  
I am more used to sourceforge than github.

Github directs to https://tools.stefankueng.com/SKTimeStamp.html to download.
The download link there goes to sourceforge:
   https://sourceforge.net/projects/stefanstools/files/SKTimeStamp/
Most recent version on sourceforge is 
  SKTimeStamp64-1.3.5.msi  2016-11-19

And the top page on Sourceforge https://sourceforge.net/projects/stefanstools/
  indicates the project has moved to Github
  https://github.com/stefankueng/tools

Documentation here on Github suggests that there should be a newer version of SKTimeStamp, at minimum, with an updated Readme showing a 2020 copyright date.

Is 1.3.5 the current release?  Or am I missing something?

Sorry for the confusion.  Thanks for any light you can shed. 

Dan

**Comment by DanLong** [comment]
Just to clarify, I'm looking for the current 64 bit windows version. 
Thanks again

**Comment by stefankueng** [comment]
the latest download for SKTimeStamp is still on sourceforge here:
https://sourceforge.net/projects/stefanstools/files/SKTimeStamp/

while the project has been moved to GitHub, there was no new release for SKTimeStamp since then, but there were commits to other projects inside that repo (there are multiple tools inside that repo, so e.g the download for StExBar is on GH here: https://github.com/stefankueng/tools/releases)
