### ISSUE TITLE
StExBar unselecting folder in Windows Explorer

### ISSUE THREAD

**Issue by rbro** [stefankueng/tools#44]
I am running into a issue I was hoping you could help give me ideas to narrow down:

I am running Windows 10 1909 and StExBar 1.11.1.1431.

In Windows Explorer if I have the StExBar toolbar enabled, if I do the below:

- double-click on a folder
- then either click the back button in the toolbar, or press Alt-Left on the keyboard to go back to the parent folder
- Windows Explorer will unselect the folder that I previously clicked on

If I hide the StExBar toolbar, then this issue doesn't occur.  When I press back, Windows Explorer continues to keep the folder as selected that I previously clicked on.

Is StExBar clearing the selected folder upon clicking back, or is there some other debugging I can do to try to figure out why it's happening?

Thank you for your help.

**Comment by stefankueng** [comment]
this doesn't happen on my machines (tested on three).

**Comment by rbro** [comment]
I've been trying to narrow it down more.  It only happens when the edit box is set to "Filter".  Can you see if it happens for you in that scenario?  Or are there other things I can do to try to figure out what is causing it?  Thanks for your help.

**Comment by micahmo** [comment]
Thanks for fixing this! I was also experiencing this issue, although my use case was slightly different from OPs. I'll add it just for visibility (in case anyone searches for a similar issue).

I navigate folders mostly by keyboard, so I often press Enter to open a folder, then press Space to select the first file/folder in the list. Because StExBar was clearing the filter every time upon navigation, the item that I had selected with my keyboard was getting deselected almost immediately.

Anyway, it is fixed in 1.11.2. Thanks!
